language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - rustup target add armv7-unknown-linux-gnueabihf
  - cargo build --target=armv7-unknown-linux-gnueabihf --verbose --all
